### ISSUE TITLE
Action fails due to "No space left on device"

### ISSUE THREAD

**Issue by ChrisCarini** [ChrisCarini/intellij-platform-plugin-verifier-action#2]
The action will fail early if there are several options passed into `ide-versions`.

Example `workflow.yml`:
```
name: IntelliJ Plugin Compatibility

on:
  push:

jobs:
  compatibility:
    name: Ensure plugin compatibility against 2020.1 & the latest EAP snapshot for both IDEA Community, IDEA Ultimate.

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Setup Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build the plugin using Gradle
        run: ./gradlew buildPlugin

      - name: Verify Plugin on IntelliJ Platforms
        id: verify
        uses: ChrisCarini/intellij-platform-plugin-verifier-action@v0.0.1
        with:
          verifier-version: '1.231'
          ide-versions: |
            ideaIC:2020.1
            ideaIU:2020.1
            ideaIC:LATEST-EAP-SNAPSHOT
            ideaIU:LATEST-EAP-SNAPSHOT
```

This will fail on the `Verify Plugin on IntelliJ Platforms` with `unzip: write: No space left on device` dueing unzipping the downloaded IDE.

Some example executions:

1. https://github.com/ChrisCarini/environment-variable-settings-summary-intellij-plugin/runs/596964147?check_suite_focus=true
1. https://github.com/ChrisCarini/jetbrains-auto-power-saver/runs/596963265?check_suite_focus=true
